version: '3.1'

services:
  ifp-mon:
    image: registry.gitlab.com/gcb77/ifp-monitor:latest
    ports: 
      - 8080:8080
    volumes: 
      - ./db:/app/db
      - ./log:/app/log
      - ./config:/app/config